### ISSUE TITLE
Add password strength meter to measure password entropy

### ISSUE THREAD

**Issue by saeedshrouf** [hydrabeer/doorkey#10]
## User Story
As a user, I want a password strength meter to identify if my current passwords pass statistical benchmarks measuring password entropy, so that I know that they are theoretically strong enough to not put me at risk of being hacked.

**Comment by HACKERALERT** [comment]
There's the zxcvbn library that does this, not sure if there is a java binding.

**Comment by saeedshrouf** [comment]
> There's the zxcvbn library that does this, not sure if there is a java binding.

Found https://github.com/nulab/zxcvbn4j will look into it, may integrate it alongside further benchmarks.

**Comment by HACKERALERT** [comment]
Completed!
