### ISSUE TITLE
Add random password generator to create true-random secure passwords

### ISSUE THREAD

**Issue by saeedshrouf** [hydrabeer/doorkey#8]
## User Story
As a user, I want a random password generator to help me come up with secure, true-random passwords generated from atmospheric data so that I know this password is as secure as possible. 

## User Interactions

**Comment by M100K300** [comment]
Is this already in progress? I can see the `SecureRandomGenerator` class in code. It already uses `java.security.SecureRandom` functionality

**Comment by saeedshrouf** [comment]
> Is this already in progress? I can see the `SecureRandomGenerator` class in code. It already uses `java.security.SecureRandom` functionality

This is already in progress, going to be PR'd very soon, it is unrelated to SecureRandomGenerator class.
